// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDACXTcj4Ym-ea-Lf8YfmQer77iYrzrrsE',
    appId: '1:741487293294:web:9a4644639357a5c90f877f',
    messagingSenderId: '741487293294',
    projectId: 'dynamo-d2114',
    authDomain: 'dynamo-d2114.firebaseapp.com',
    storageBucket: 'dynamo-d2114.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmnfsNTOcNE1oVKNZIV30FqGBqPY89CTs',
    appId: '1:741487293294:android:1e954f70755351810f877f',
    messagingSenderId: '741487293294',
    projectId: 'dynamo-d2114',
    storageBucket: 'dynamo-d2114.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR-AFgS5hBPfkGP39mu4cOZ0VgOI-r9gs',
    appId: '1:741487293294:ios:9baabc26843031e20f877f',
    messagingSenderId: '741487293294',
    projectId: 'dynamo-d2114',
    storageBucket: 'dynamo-d2114.appspot.com',
    iosBundleId: 'com.example.mindlink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR-AFgS5hBPfkGP39mu4cOZ0VgOI-r9gs',
    appId: '1:741487293294:ios:9baabc26843031e20f877f',
    messagingSenderId: '741487293294',
    projectId: 'dynamo-d2114',
    storageBucket: 'dynamo-d2114.appspot.com',
    iosBundleId: 'com.example.mindlink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDACXTcj4Ym-ea-Lf8YfmQer77iYrzrrsE',
    appId: '1:741487293294:web:d35e5aa5a92c0ea00f877f',
    messagingSenderId: '741487293294',
    projectId: 'dynamo-d2114',
    authDomain: 'dynamo-d2114.firebaseapp.com',
    storageBucket: 'dynamo-d2114.appspot.com',
  );

}